services:
  postgres:
    image: postgres:17
    container_name: postgres_api_tickets
    environment:
      POSTGRES_DB: api_tickets_suporte
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - dados_postgres_tickets:/var/lib/postgresql/data

volumes:
  dados_postgres_tickets: